README.md
main.go

Rename newly introduced metrics to get more consistency.

Metrics name consistency (oracle_tablespace -> oracledb_tablespace).

---

README.md
main.go

Use only one request to retrieve active and inactive sessions.
Add a new information about session type (USER or BACKGROUND).
Update README to reflect change in metrics name.

Change the way we retrieve information on sessions activity.

---

README.md
main.go

This feature can be useful when using a heavily loaded database or a
database that authenticates using an external mechanism. Database
connection failure may happen in those two cases. Keeping some idle
connections will prevent the exporter from going down.
We do recommend first trying with the default values since they test if
it is still possible to open a new connection.
NOTE: I did not have time yet to test the binary becasue I haven't been able to setup my workstation correctly to build the binary and test it.

feat: Add flag to allow user to maxidle and max open connection on the DB connection pool

---

README.md

Fix Oracle XE docker image due to DMCA Takedown issue (see https://github.com/wnameless/docker-oracle-xe-11g)

Fix Oracle XE docker image

---

default-metrics.toml

The tablespace query takes over 30-35 seconds most of the time we run it on our systems, so it doesn't reliably get data into the scrape. This query yields identical numbers to the existing query, but returns in less than a second.

Faster tablespace utilization query

---

default-metrics.toml

The current `default_metrics.toml` is querying the `v$asm_diskgroup` table. While this gets what we want it is far more intensive than it needs to be on the host server and it is not what this table is meant for. This PR updates the ASM default metric to query the `v$asm_diskgroup_stat` table instead. This `_stat` table is there for the purpose of performance monitoring. Look ups are quicker and less intense on the host machine.
As it stands now, this default metric forces the host machine to perform a discovery of all ASM diskgroups in order to find any potentially new diskgroups. While this is obviously useful in some cases, for the purpose of _monitoring_ it is not useful and can be harmful if a cluster has a large number of diskgroups it needs to rediscover. …

Using `_stat` table for ASM diskgroup checks

---

main.go

Enabling http error logging is useful to resolve "500 Error" from prometheus

Error handling

---

main.go
metric-histogram-example.toml

I really want to be able to do some metrics with histograms. I took a stab at it below. This accomplishes that.
There's a few decisions I made that don't _exactly_ fit with the code patterns you established for counters/gauges. Specifically, in the ScrapeGenericValues section, I feel like the GetMetricType function should be more useful to determine if the metric is a Histogram, but there's no equivalent prometheus.ValueType for a histogram. So if that function were modified to support Histograms, it's likely that you wouldn't be able to use it to specify the metric type in the MustNewConstMetric calls.
There's also a bit more code duplication than I'd like since the Histograms require so much more work to prepare in the if/else block deciding about fieldToAppend.
I'm open to feedback if …

Adding support for histograms

---

go.mod

Hit some segfaults upon freeing memory occasionally while running:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2e94b90 pc=0x7f3c6d83cbb7]
runtime stack:
runtime.throw(0x94d4c2, 0x2a)
/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:679 +0x46a
goroutine 4554 [syscall]:
runtime.cgocall(0x842e40, 0xc000155580, 0xc000000000)
/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000155550 sp=0xc000155518 pc=0x40687b
github.com/mattn/go-oci8._Cfunc_OCIHandleFree(0x2e94b90, 0x2, 0x0)
_cgo_gotypes.go:419 +0x4d fp=0xc000155580 sp=0xc000155550 pc=0x7206ed
github.com/mattn/go-oci8.(*OCI8Conn).Close.func3(0xc00025f500, 0x0)
/go/pkg/mod/github.com/mattn/go-oci8@v0.0.0-20160329132525-7a6ecfe0eedf/oci8.go:563 +0x5e fp=0xc0001555b8 …
```

Updating to latest version of go-oci8 library because of seg-faults

---

go.sum
main.go

1) Added reloading metrics after changing of custom-metrics.toml (for example, to fix SQL or add new metric).
2) Using "ErrorHandling: promhttp.ContinueOnError" as default.
3) Measure time for each SQL request (in debug mode).

Reload on metrics change, promhttp.ContinueOnError as default, measuring time for each SQL-request

---

README.md

Hi!
I spend some time to solving issue with connection to primary/standby database. The information in readme.md was quite poor.  So i suggest to add more comments.
Also i setup oracledb_exported as RedHat 7 systemd daemon. Additional changes was required to make it working

Enhancement to Readme.md: oracle ezconnect and systemd integration

---

README.md
default-asm-metrics.toml
systemd-example/oracleasm_exporter.service
systemd-example/oracledb_exporter.service

Hi
I fixed :
- my bug with #170 
- password :)
- added ASM connection example - requires AS SYSDBA for special asmsnmp user
- added systemd configuration example for oracledb_exporter and oracleasm_exporter
Hope, this helps to others

Changes to Readme; System D examples

---

README.md
default-metrics.toml

Exposes used_percent from dba_tablespace_usage_metrics.  This percentage is more accurate than calculating the percentage from the other exposed metrics because it includes reclaimable space in the calculation.

#219 add oracledb_tablespace_used_percent metric

---

README.md

I faced an issue when trying to scrape data due to using a low privileged user, so i added the required privs for people to consider granting them.

Added default-metrics privileges requirement

---

.github/workflows/pull-request-cleanup-manual.yml
.github/workflows/pull-request-cleanup.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

Fixes GitHub release failed with status: 403

fix: fix GitHub release failed with status: 403

---

Dockerfile
alpine/Dockerfile
oraclelinux/Dockerfile

Use a parameter to set oracle client image

:wrench: Use a parameter to set oracle client version

---

collector/collector.go

When metric scrape fails, instead of SQL error  only "unsupported value type" is logged.
Fixes #343
Started locally with custom-metrics.toml which includes sql query that produces error
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation

Log SQL error message

---

custom-metrics-example/custom-metrics.toml

Adding two new metrics that can be useful for DBA's:
`oracledb_cache_hit_ratio_percentage`
`oracledb_startup_time_seconds`
Being tested in XE instance version 21c

Add cache_hit_ratio and startup_time metrics

---

.pre-commit-config.yaml
collector/collector.go

Hello,
Well done on creating this exporter. 
Also, added a pre-commit hook. To install it:
```
go install github.com/go-critic/go-critic/cmd/gocritic@latest go install golang.org/x/tools/cmd/goimports@latest go install golang.org/x/lint/golint@latest
go install github.com/gordonklaus/ineffassign@latest pip install pre-commit
pre-commit install
```
It will then run on every `git commit` invocation. To run manually on all files, invoke: `pre-commit run --all-files`
Following the merge of this pull, the only issue that will be reported is:
> ./main.go:85:3: exitAfterDefer: os.Exit will exit, and `defer cancel()` will not run
Please see discussion in https://github.com/go-critic/go-critic/issues/1022 for ways to address this.
Cheers,

Use strings.ReplaceAll() rather than strings.Replace() with -1

---

README.md
main.go

Another way to configure DSN. 
This is relevant for Windows systems, where it is difficult to forward an environment variable
- [+] New feature (non-breaking change which adds functionality)
It worked on Winodws with OracleDB
Test where dsn was output to the console
- [+] My code follows the style guidelines of this project
- [+ ] I have performed a self-review of my own code
- [+ ] I have commented my code, particularly in hard-to-understand areas
- [+ ] I have made corresponding changes to the documentation
- [+ ] My changes generate no new warnings
- [+ ] I have added tests that prove my fix is effective or that my feature works
- [+ ] New and existing unit tests pass locally with my changes
- [+ ] Any dependent changes have been merged and published in downstream modules
- [+ ] …

Add flag for configuration DSN

---

.dockerignore
Makefile
README.md
collector/collector.go
collector/default_metrics.go
custom-metrics-example/custom-metrics.yaml
default-metrics.yaml
go.mod
go.sum
main.go
operating-principles.md

* Added yaml parser for more readable configs. toml is also still supported.
* Enchanced log messages: use key-value syntax, added warning message when fallback to hard-coded default metrics
* Updated readme with some tips from my experience with the oracledb exporter (which I find anyway cool).
```
make local-build
export DATA_SOURCE_NAME="<connectionstring-to-oracle-19.21.0.0.0>"
dist/oracledb_exporter-0.5.2.linux-amd64/oracledb_exporter --default.metrics=./default-metrics.toml --log.level debug
dist/oracledb_exporter-0.5.2.linux-amd64/oracledb_exporter --custom.metrics=./custom-metrics-example/custom-metrics.toml --log.level debug
curl http://localhost:9161
dist/oracledb_exporter-0.5.2.linux-amd64/oracledb_exporter --default.metrics=./default-metrics.yaml --log.level debug …
```

Added support for yaml-formatted configs

---

Dockerfile
Makefile
README.md

This change adds support for the Scratch image. Docker image sizes after a `make docker`:
<pre>
iamseth/oracledb_exporter                      0.6.0-oraclelinux_legacy-tablespace   25f1e02b4c1b   6 minutes ago    137MB
iamseth/oracledb_exporter                      0.6.0-oraclelinux                     4e01e343f297   6 minutes ago    137MB
iamseth/oracledb_exporter                      oraclelinux                           4e01e343f297   6 minutes ago    137MB
iamseth/oracledb_exporter                      0.6.0-alpine                          356dfb18f4a0   7 minutes ago    33.2MB
iamseth/oracledb_exporter                      alpine                                356dfb18f4a0   7 minutes ago    33.2MB
iamseth/oracledb_exporter                      0.6.0-alpine_legacy-tablespace …

Add scratch image

---

README.md
main.go

Fixes #428
1. Created a local file dsn.txt with content "oracle://username:password@host:1521/instance"
2. Executed `go run main.go --database.dsnFile=./dsn.txt`
3. Opened http://localhost:9161/metrics and verified oracledb_tablespace_bytes metrics are present
- [] I have commented my code, particularly in hard-to-understand areas

Support for reading data source from file

---

collector/collector.go
collector/collector_test.go
go.mod
go.sum

Parse Dsn URL before trying to connect to be avoid printing user/password. When trying to connect via a malformed Dsn URL, the exporter logs something like this:
`caller=collector.go:263 level=error errorpingingoracle:="parse \"oracle://user:password@\\oracleserver.com:1556/sdfef\": net/url: invalid control character in URL"`
As this is treated as a generic error, the maskDsn function is not used.
Fixes # (issue)
A test has been added

Parse Dsn URL to handle user/password masking

---

collector/collector.go

Fixes # 459
Ran this version for 3 weeks for 36 databases

Fix for iamseth/oracledb_exporter#459

---

README.md
default-metrics.legacy-tablespace.toml
default-metrics.toml

Prometheus metric naming best practices not followed for metric name "oracledb_tablespace_free"
Fixes #372 
Renamed the metric in toml file and I am using it in production.

Fix metric name
